version: '3.4'

services:
  mongodb:
    image: mongo:4.0.3
    volumes:
      - ./scripts/docker-mongo-init.sh:/docker-mongo-init.sh:ro
    entrypoint: ['/bin/bash', '/docker-mongo-init.sh']
    ports:
      - '27018:27018'

  maildev:
    image: maildev/maildev
    ports:
      - '1080:1080'
      - '1025:1025'
